import React, { useEffect, useState } from "react";
import { View, Text, StyleSheet, ActivityIndicator } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { CheckCircle2, Clock, AlertTriangle } from "lucide-react-native";
import { supabase } from "../lib/supabase";
import { useTheme } from "../lib/ThemeContext";
import { Button } from "../components/ui/Button";
import { spacing, radius } from "../lib/theme";

type Status = "checking" | "completed" | "pending" | "error";

export default function PaymentSuccessScreen() {
  const params = useLocalSearchParams<{ session_id?: string }>();
  const router = useRouter();
  const { theme } = useTheme();
  const c = theme.colors;

  const [status, setStatus] = useState<Status>("checking");
  const [message, setMessage] = useState<string>("");

  useEffect(() => {
    const sessionId = params.session_id;
    if (!sessionId) {
      setStatus("error");
      setMessage("Missing checkout session id.");
      return;
    }

    // Demo session IDs (generated by the in-app mock checkout) never touch
    // Supabase or Stripe — flip straight to the success state so the demo
    // reads as a completed purchase.
    if (sessionId.startsWith("demo-")) {
      const showSuccess = setTimeout(() => setStatus("completed"), 400);
      return () => clearTimeout(showSuccess);
    }

    let cancelled = false;
    let hardTimeout: ReturnType<typeof setTimeout> | null = null;

    // 1. Immediate check — webhook may already have landed.
    // 2. Realtime subscription — react the instant the row flips.
    // 3. 45s hard timeout — fall back to "pending" UX.
    const channel = supabase
      .channel(`payment-${sessionId}`)
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "payments",
          filter: `stripe_checkout_session_id=eq.${sessionId}`,
        },
        (payload) => {
          const newStatus = (payload.new as { status?: string })?.status;
          if (newStatus === "completed" && !cancelled) setStatus("completed");
          if (newStatus === "failed" && !cancelled) {
            setStatus("error");
            setMessage("Payment failed. No charge was made.");
          }
        }
      )
      .subscribe();

    (async () => {
      const { data, error } = await supabase
        .from("payments")
        .select("status")
        .eq("stripe_checkout_session_id", sessionId)
        .maybeSingle();
      if (cancelled) return;
      if (error) {
        setStatus("error");
        setMessage(error.message);
        return;
      }
      if (data?.status === "completed") setStatus("completed");
      if (data?.status === "failed") {
        setStatus("error");
        setMessage("Payment failed. No charge was made.");
      }
    })();

    hardTimeout = setTimeout(() => {
      if (!cancelled) {
        setStatus((s) =>
          s === "checking" ? "pending" : s
        );
        setMessage(
          "Payment is processing. You'll see it in your orders once Stripe confirms."
        );
      }
    }, 45_000);

    return () => {
      cancelled = true;
      if (hardTimeout) clearTimeout(hardTimeout);
      supabase.removeChannel(channel);
    };
  }, [params.session_id]);

  const iconSize = 56;
  return (
    <View style={[styles.container, { backgroundColor: c.background }]}>
      <View style={styles.inner}>
        {status === "checking" && (
          <>
            <View
              style={[
                styles.iconRing,
                { borderColor: c.accent500, backgroundColor: c.accentSurface },
              ]}
            >
              <ActivityIndicator color={c.accent500} size="large" />
            </View>
            <Text style={[styles.title, { color: c.textPrimary, fontFamily: theme.typography.title.fontFamily }]}>
              Finalizing your payment
            </Text>
            <Text style={[styles.body, { color: c.textSecondary }]}>
              We're confirming the transaction with Stripe. This should only take a few seconds.
            </Text>
          </>
        )}
        {status === "completed" && (
          <>
            <View
              style={[
                styles.iconRing,
                { borderColor: c.success, backgroundColor: "rgba(52,211,153,0.12)" },
              ]}
            >
              <CheckCircle2 size={iconSize} color={c.success} strokeWidth={1.6} />
            </View>
            <Text style={[styles.title, { color: c.textPrimary, fontFamily: theme.typography.title.fontFamily }]}>
              Payment successful
            </Text>
            <Text style={[styles.body, { color: c.textSecondary }]}>
              Your purchase has been recorded. Check your orders for the receipt.
            </Text>
          </>
        )}
        {status === "pending" && (
          <>
            <View
              style={[
                styles.iconRing,
                { borderColor: c.warning, backgroundColor: "rgba(251,191,36,0.12)" },
              ]}
            >
              <Clock size={iconSize} color={c.warning} strokeWidth={1.6} />
            </View>
            <Text style={[styles.title, { color: c.textPrimary, fontFamily: theme.typography.title.fontFamily }]}>
              Almost there
            </Text>
            <Text style={[styles.body, { color: c.textSecondary }]}>{message}</Text>
          </>
        )}
        {status === "error" && (
          <>
            <View
              style={[
                styles.iconRing,
                { borderColor: c.error, backgroundColor: "rgba(248,113,113,0.12)" },
              ]}
            >
              <AlertTriangle size={iconSize} color={c.error} strokeWidth={1.6} />
            </View>
            <Text style={[styles.title, { color: c.textPrimary, fontFamily: theme.typography.title.fontFamily }]}>
              Something went wrong
            </Text>
            <Text style={[styles.body, { color: c.textSecondary }]}>{message}</Text>
          </>
        )}
      </View>

      <View style={styles.footer}>
        <Button
          label="Back to home"
          variant="primary"
          onPress={() => router.replace("/")}
          fullWidth
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
  },
  inner: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
  },
  iconRing: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.md,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    textAlign: "center",
    letterSpacing: -0.3,
  },
  body: {
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    maxWidth: 320,
  },
  footer: {
    paddingTop: spacing.md,
  },
});
